### ISSUE TITLE
Symbol's function definition is void: citar-select-ref

### ISSUE THREAD

**Issue by arnabkdey** [jethrokuan/org-roam-guide#1]
Hi, I am trying to implement the custom function "jethro/org-roam-node-from-cite" in my config so I can create a reference citation zettel. I use the following snippent from the blog

`(defun jethro/org-roam-node-from-cite (keys-entries)
    (interactive (list (citar-select-ref :multiple nil :rebuild-cache t)))
    (let ((title (citar--format-entry-no-widths (cdr keys-entries)
                                                "${author editor} :: ${title}")))
      (org-roam-capture- :templates
                         '(("r" "reference" plain "%?" :if-new
                            (file+head "reference/${citekey}.org"
                                       ":PROPERTIES:
:ROAM_REFS: [cite:@${citekey}]
:END:
#+title: ${title}\n")
                            :immediate-finish t
                            :unnarrowed t))
                         :info (list :citekey (car keys-entries))
                         :node (org-roam-node-create :title title)
                         :props '(:finalize find-file))))`

When I call the function, it returns the following error:

`Symbol’s function definition is void: citar-select-ref`

**Comment by jethrokuan** [comment]
You'll need the citar package from MELPA: https://melpa.org/#/citar
